### PR TITLE
Add scraping airbnb

### PR DESCRIPTION
**Pull request by nfilzi**

### CODE REVIEW

**Comment by cveneziani** [comment]
That's weird, I also see my changes 🤔 
Can you fix that?

**Comment by nfilzi** [comment]
I guess that happened when I rebased `master` into my `add-airbnb-scraping` branch. As usual, I don't get what it does. I'm willing to fix it, but what do you mean exactly by fix it? :)

**Comment by cveneziani** [comment]
By making sure that my commits do not appear in this PR

**Comment by nfilzi** [comment]
How do you do that?

**Pull request closed without merging**
