### PR TITLE
Fix homepage navbar

### PR DESCRIPTION
**Pull request by cveneziani**
- Do not keep two separate navbars
- Use the navbar partial, just hide the cta button
- Fix the weird behavior on hover of links

### CODE REVIEW

**Comment by nfilzi** [comment]
ça remue toujours son popotin les liens sous Chrome 😅

**Comment by nfilzi** [comment]
Position of the Sign In is strange:

screen shot 2017-10-04 at 01 08 18

**Comment by nfilzi** [comment]
When you click on the avatar to get access to dropdown, the avatar raises up in the air

**Comment by cveneziani** [comment]
Well, I'll have a second look at it.

**Comment by nfilzi** [comment]
http://recordit.co/CMesGbTLyo

**Comment by cveneziani** [comment]
Fix done, let's hope!

**Comment by nfilzi** [comment]
🎉 It works!

**Comment by cveneziani** [comment]
Woot! Then is it approved? 😃

**Pull request merged**
